# Generated by Django 5.2.8 on 2026-01-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_titels', models.CharField(max_length=100)),
                ('topic_views', models.IntegerField()),
                ('topic_topik', models.TextField()),
                ('topic_image', models.ImageField(upload_to='')),
                ('topic_date', models.DateTimeField()),
            ],
        ),
    ]
