# Generated by Django 5.2.8 on 2026-01-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_titels',
            new_name='topic_titel',
        ),
    ]
