# Generated by Django 5.2.8 on 2026-01-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0002_rename_topic_titels_topic_topic_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_titel',
            new_name='topic_title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_topik',
            new_name='topic_topic',
        ),
    ]
