# Generated by Django 5.2.8 on 2026-02-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0003_rename_topic_titel_topic_topic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cortez_type',
            field=models.CharField(choices=[('Типа ключ нужный для джанго', 'Любое значение '), ('бн', 'бан'), ('врбн', 'временый бан')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
