# Generated by Django 6.0.3 on 2026-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0004_topic_cortez_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='cortez_type',
        ),
        migrations.AddField(
            model_name='topic',
            name='themes_type',
            field=models.CharField(choices=[('Плтк', 'Политика'), ('Лчн', 'Личное'), ('Жвт', 'Животные'), ('Игр', 'Игры')], default='Игр', max_length=100),
            preserve_default=False,
        ),
    ]
