# Generated by Django 6.0.3 on 2026-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0005_remove_topic_cortez_type_topic_themes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='themes_type',
            field=models.CharField(choices=[('politics', 'Политика'), ('personal', 'Личное'), ('animals', 'Животные'), ('game', 'Игры')], max_length=100),
        ),
    ]
