# Generated by Django 5.2.8 on 2026-06-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proect_info_progra_app', '0009_answercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='comment',
            new_name='answer_comment',
        ),
    ]
